// Generated by Scripts/AuthorStationRefresh.py from measured licensed mesh bounds.
// Presentation only. Keep SSStation collision and service locations authoritative.
#include "Misc/PackageName.h"
#include "SSStationPresentation.h"
bool ASSStation::BuildLicensedShell()
{
    const TCHAR *Paths[] = {
        TEXT("/Game/SciFiCorridor/Meshes/SM_Celling_01.SM_Celling_01"),
        TEXT("/Game/SciFiCorridor/Meshes/SM_Crate.SM_Crate"),
        TEXT("/Game/SciFiCorridor/Meshes/SM_Floor_01.SM_Floor_01"),
        TEXT("/Game/SciFiCorridor/Meshes/SM_LampCelling.SM_LampCelling"),
        TEXT("/Game/SciFiCorridor/Meshes/SM_Monitor.SM_Monitor"),
        TEXT("/Game/SciFiCorridor/Meshes/SM_MonitorScreen.SM_MonitorScreen"),
        TEXT("/Game/SciFiCorridor/Meshes/SM_Top_Wall02.SM_Top_Wall02"),
        TEXT("/Game/SciFiCorridor/Meshes/SM_Wall_03.SM_Wall_03"),
    };
    TArray<UStaticMesh *> Meshes;
    for (const TCHAR *Path : Paths)
    {
        if (!FPackageName::DoesPackageExist(FPackageName::ObjectPathToPackageName(FString(Path))))
            return false;
        auto *Mesh = LoadObject<UStaticMesh>(nullptr, Path);
        if (!Mesh)
            return false;
        Meshes.Add(Mesh);
    }
    // These two vendor meshes ship with an unassigned material slot.
    // Resolve matching kit materials before creating any components.
    TArray<UMaterialInterface *> MissingSlotMaterials;
    MissingSlotMaterials.SetNumZeroed(Meshes.Num());
    for (int32 Index = 0; Index < Meshes.Num(); ++Index)
    {
        for (const auto &Slot : Meshes[Index]->GetStaticMaterials())
        {
            if (Slot.MaterialInterface)
                continue;
            const TCHAR *FallbackPath = nullptr;
            if (Meshes[Index]->GetFName() == TEXT("SM_MonitorScreen"))
                FallbackPath = TEXT("/Game/SciFiCorridor/Materials/MI_MonitorError_Inst2.MI_MonitorError_Inst2");
            else if (Meshes[Index]->GetFName() == TEXT("SM_Top_Wall02"))
                FallbackPath = TEXT("/Game/SciFiCorridor/Materials/MI_CorridorWall_02.MI_CorridorWall_02");
            if (!FallbackPath || !FPackageName::DoesPackageExist(FPackageName::ObjectPathToPackageName(FString(FallbackPath))))
                return false;
            MissingSlotMaterials[Index] = LoadObject<UMaterialInterface>(nullptr, FallbackPath);
            if (!MissingSlotMaterials[Index])
                return false;
        }
    }
    TArray<UInstancedStaticMeshComponent *> Batches;
    for (int32 Index = 0; Index < Meshes.Num(); ++Index)
    {
        auto *Batch = NewObject<UInstancedStaticMeshComponent>(this, FName(*FString::Printf(TEXT("LicensedStation_%d"), Index)));
        Batch->SetupAttachment(RootComponent);
        Batch->SetStaticMesh(Meshes[Index]);
        const auto &Materials = Meshes[Index]->GetStaticMaterials();
        for (int32 Slot = 0; Slot < Materials.Num(); ++Slot)
            Batch->SetMaterial(Slot, SSStationPresentation::InstancedMaterial(Materials[Slot].MaterialInterface ? Materials[Slot].MaterialInterface.Get() : MissingSlotMaterials[Index]));
        if (Meshes[Index]->GetFName() == TEXT("SM_MonitorScreen"))
        {
            const TCHAR *ScreenPath = TEXT("/Game/SpaceSurvival/Licensed/StationVisualPass/Screens/M_ServiceScreen");
            if (FPackageName::DoesPackageExist(ScreenPath))
                if (auto *Screen = LoadObject<UMaterialInterface>(nullptr, ScreenPath))
                    Batch->SetMaterial(0, Screen);
        }
        Batch->SetCollisionProfileName(TEXT("NoCollision"));
        Batch->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        Batch->SetGenerateOverlapEvents(false);
        Batch->SetCanEverAffectNavigation(false);
        Batch->SetMobility(EComponentMobility::Movable);
        Batch->RegisterComponent();
        Geometry.Add(Batch);
        Batches.Add(Batch);
    }
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1600.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1600.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1600.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1600.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1600.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1600.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1400.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1400.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1400.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1400.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1400.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1400.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1200.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1200.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1200.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1200.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1200.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1200.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1000.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1000.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1000.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1000.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1000.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1000.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-800.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-800.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-800.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-800.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-800.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-800.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-600.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-600.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-600.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-600.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-600.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-600.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-400.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-400.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-400.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-400.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-400.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-400.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-200.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-200.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-200.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-200.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-200.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-200.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(200.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(200.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(200.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(200.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(200.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(200.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(400.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(400.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(400.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(400.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(400.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(400.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(600.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(600.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(600.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(600.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(600.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(600.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(800.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(800.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(800.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(800.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(800.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(800.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1000.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1000.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1000.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1000.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1000.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1000.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1200.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1200.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1200.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1200.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1200.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1200.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1400.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1400.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1400.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1400.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1400.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1400.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1600.000000000, -1166.671123144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1600.000000000, -700.004456144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1600.000000000, -233.337789144, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1600.000000000, 233.328877856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1600.000000000, 699.995544856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[2]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1600.000000000, 1166.662211856, -15.245445439), FVector(1.000000000, 1.035595270, 0.999433658)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-1134.344616191, -1369.838975761, 0.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-1134.344616191, -1369.838975761, 300.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-1134.344616191, -1369.838975761, 600.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-567.677949191, -1369.838975761, 0.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-567.677949191, -1369.838975761, 300.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-567.677949191, -1369.838975761, 600.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-1.011282191, -1369.838975761, 0.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-1.011282191, -1369.838975761, 300.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-1.011282191, -1369.838975761, 600.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(565.655384809, -1369.838975761, 0.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(565.655384809, -1369.838975761, 300.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(565.655384809, -1369.838975761, 600.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(1132.322051809, -1369.838975761, 0.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(1132.322051809, -1369.838975761, 300.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(1132.322051809, -1369.838975761, 600.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(1698.988718809, -1369.838975761, 0.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(1698.988718809, -1369.838975761, 300.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(1698.988718809, -1369.838975761, 600.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(-1684.919487880, -1448.661537616, 0.000029795), FVector(1.389385605, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(-1684.919487880, -1448.661537616, 300.000029795), FVector(1.389385605, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(-1684.919487880, -1448.661537616, 600.000029795), FVector(1.389385605, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1698.988717809, 1369.838975761, 0.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1698.988717809, 1369.838975761, 300.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1698.988717809, 1369.838975761, 600.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1132.322050809, 1369.838975761, 0.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1132.322050809, 1369.838975761, 300.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1132.322050809, 1369.838975761, 600.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-565.655383809, 1369.838975761, 0.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-565.655383809, 1369.838975761, 300.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-565.655383809, 1369.838975761, 600.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1.011283191, 1369.838975761, 0.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1.011283191, 1369.838975761, 300.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1.011283191, 1369.838975761, 600.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(567.677950191, 1369.838975761, 0.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(567.677950191, 1369.838975761, 300.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(567.677950191, 1369.838975761, 600.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1134.344617191, 1369.838975761, 0.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1134.344617191, 1369.838975761, 300.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1134.344617191, 1369.838975761, 600.000029795), FVector(1.049758013, 0.996551696, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(-1684.919487880, 701.338462384, 0.000029795), FVector(1.389385605, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(-1684.919487880, 701.338462384, 300.000029795), FVector(1.389385605, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(-1684.919487880, 701.338462384, 600.000029795), FVector(1.389385605, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, -1399.000614753, 0.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, -1399.000614753, 300.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, -1399.000614753, 600.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, -839.000614753, 0.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, -839.000614753, 300.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, -839.000614753, 600.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, -279.000614753, 0.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, -279.000614753, 300.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, -279.000614753, 600.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, 280.999385247, 0.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, 280.999385247, 300.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, 280.999385247, 600.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, 840.999385247, 0.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, 840.999385247, 300.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[7]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1725.080512120, 840.999385247, 600.000029795), FVector(1.037407918, 0.498275848, 0.976329395)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1545.450598968, -1166.666667000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1545.450598968, -700.000000000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1545.450598968, -233.333333000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1545.450598968, 233.333334000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1545.450598968, 700.000001000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1545.450598968, 1166.666668000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1236.359689968, -1166.666667000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1236.359689968, -700.000000000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1236.359689968, -233.333333000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1236.359689968, 233.333334000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1236.359689968, 700.000001000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1236.359689968, 1166.666668000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-927.268780968, -1166.666667000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-927.268780968, -700.000000000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-927.268780968, -233.333333000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-927.268780968, 233.333334000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-927.268780968, 700.000001000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-927.268780968, 1166.666668000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-618.177871968, -1166.666667000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-618.177871968, -700.000000000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-618.177871968, -233.333333000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-618.177871968, 233.333334000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-618.177871968, 700.000001000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-618.177871968, 1166.666668000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-309.086962968, -1166.666667000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-309.086962968, -700.000000000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-309.086962968, -233.333333000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-309.086962968, 233.333334000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-309.086962968, 700.000001000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-309.086962968, 1166.666668000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.003946032, -1166.666667000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.003946032, -700.000000000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.003946032, -233.333333000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.003946032, 233.333334000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.003946032, 700.000001000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.003946032, 1166.666668000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(309.094855032, -1166.666667000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(309.094855032, -700.000000000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(309.094855032, -233.333333000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(309.094855032, 233.333334000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(309.094855032, 700.000001000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(309.094855032, 1166.666668000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(618.185764032, -1166.666667000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(618.185764032, -700.000000000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(618.185764032, -233.333333000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(618.185764032, 233.333334000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(618.185764032, 700.000001000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(618.185764032, 1166.666668000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(927.276673032, -1166.666667000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(927.276673032, -700.000000000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(927.276673032, -233.333333000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(927.276673032, 233.333334000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(927.276673032, 700.000001000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(927.276673032, 1166.666668000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1236.367582032, -1166.666667000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1236.367582032, -700.000000000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1236.367582032, -233.333333000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1236.367582032, 233.333334000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1236.367582032, 700.000001000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1236.367582032, 1166.666668000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1545.458491032, -1166.666667000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1545.458491032, -700.000000000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1545.458491032, -233.333333000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1545.458491032, 233.333334000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1545.458491032, 700.000001000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[0]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1545.458491032, 1166.666668000, 1026.776591195), FVector(1.030307432, 0.910594049, 0.997810536)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-1391.505864074, -1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-1082.414955074, -1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-773.324046074, -1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-464.233137074, -1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-155.142228074, -1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(153.948680926, -1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(463.039589926, -1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(772.130498926, -1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(1081.221407926, -1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(1390.312316926, -1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(1699.403225926, -1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1699.403225926, 1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1390.312316926, 1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1081.221407926, 1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-772.130498926, 1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-463.039589926, 1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-153.948680926, 1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(155.142228074, 1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(464.233137074, 1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(773.324046074, 1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1082.414955074, 1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1391.505864074, 1372.000007639, 900.129743634), FVector(1.030543410, 1.001319444, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1734.999993179, -1399.399325445, 900.129743634), FVector(1.037278988, 0.894035218, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1734.999993179, -1088.288214445, 900.129743634), FVector(1.037278988, 0.894035218, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1734.999993179, -777.177103445, 900.129743634), FVector(1.037278988, 0.894035218, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1734.999993179, -466.065992445, 900.129743634), FVector(1.037278988, 0.894035218, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1734.999993179, -154.954881445, 900.129743634), FVector(1.037278988, 0.894035218, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1734.999993179, 156.156229555, 900.129743634), FVector(1.037278988, 0.894035218, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1734.999993179, 467.267340555, 900.129743634), FVector(1.037278988, 0.894035218, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1734.999993179, 778.378451555, 900.129743634), FVector(1.037278988, 0.894035218, 1.950593023)));
    Batches[6]->AddInstance(FTransform(FRotator(0, 90, 0), FVector(1734.999993179, 1089.489562555, 900.129743634), FVector(1.037278988, 0.894035218, 1.950593023)));
    Batches[4]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-800.000003815, -1325.000000000, 190.000000000), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[5]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-799.569549561, -1324.009699821, 190.325872421), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[4]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(199.999996185, -1325.000000000, 190.000000000), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[5]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(200.430450439, -1324.009699821, 190.325872421), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[4]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-1099.999996185, 1325.000000000, 190.000000000), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[5]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-1100.430450439, 1324.009699821, 190.325872421), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[4]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(0.000003815, 1325.000000000, 190.000000000), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[5]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(-0.430450439, 1324.009699821, 190.325872421), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[4]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(1000.000003815, 1325.000000000, 190.000000000), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[5]->AddInstance(FTransform(FRotator(0, 180, 0), FVector(999.569549561, 1324.009699821, 190.325872421), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[1]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1502.193489075, -1170.351554871, 60.064022064), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[1]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1502.193489075, -1000.351554871, 60.064022064), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[1]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1447.806510925, -1200.351554871, 60.064022064), FVector(1.000000000, 1.000000000, 1.000000000)));
    Batches[3]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1200.000000000, -950.000000000, 990.000000477), FVector(2.000000000, 2.000000000, 2.000000000)));
    Batches[3]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-1200.000000000, 950.000000000, 990.000000477), FVector(2.000000000, 2.000000000, 2.000000000)));
    Batches[3]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-600.000000000, -950.000000000, 990.000000477), FVector(2.000000000, 2.000000000, 2.000000000)));
    Batches[3]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(-600.000000000, 950.000000000, 990.000000477), FVector(2.000000000, 2.000000000, 2.000000000)));
    Batches[3]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.000000000, -950.000000000, 990.000000477), FVector(2.000000000, 2.000000000, 2.000000000)));
    Batches[3]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(0.000000000, 950.000000000, 990.000000477), FVector(2.000000000, 2.000000000, 2.000000000)));
    Batches[3]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(600.000000000, -950.000000000, 990.000000477), FVector(2.000000000, 2.000000000, 2.000000000)));
    Batches[3]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(600.000000000, 950.000000000, 990.000000477), FVector(2.000000000, 2.000000000, 2.000000000)));
    Batches[3]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1200.000000000, -950.000000000, 990.000000477), FVector(2.000000000, 2.000000000, 2.000000000)));
    Batches[3]->AddInstance(FTransform(FRotator(0, 0, 0), FVector(1200.000000000, 950.000000000, 990.000000477), FVector(2.000000000, 2.000000000, 2.000000000)));
    SSStationPresentation::BuildDetails(this, Geometry);
    return true;
}
