// Generated by Scripts/GenerateStationPitStopBoxes.py from Artifacts/StationPitStop/keel/PitStop.json.
// Station-local centimetres: centre then half-extent. Do not edit; regenerate.
// Source blend sha256 3913fd79109fa0fa, glb sha256 ec3fcae7d8534784, Y sign -1 (from Import.json).
static const struct { const TCHAR *Name; FVector Center; FVector Extent; } SSStationPitStopBoxes[] = {
    {TEXT("Keel_Floor"), FVector(450, 0, -390), FVector(2350, 2500, 310)},
    {TEXT("Keel_Roof"), FVector(450, 0, 1415), FVector(2350, 2500, 385)},
    {TEXT("Keel_Port"), FVector(450, -1975, 475), FVector(2350, 525, 555)},
    {TEXT("Keel_Stbd"), FVector(450, 1975, 475), FVector(2350, 525, 555)},
    {TEXT("Keel_Stern"), FVector(2350, 0, 475), FVector(450, 1450, 555)},
    {TEXT("Bow_Port"), FVector(-1800, -1075, 475), FVector(100, 375, 555)},
    {TEXT("Bow_Stbd"), FVector(-1800, 1075, 475), FVector(100, 375, 555)},
    {TEXT("Bow_Lintel"), FVector(-1800, 0, 999), FVector(100, 700, 31)},
    {TEXT("Bow_Sill"), FVector(-1800, 0, -45), FVector(100, 700, 35)},
    {TEXT("Fin_Port"), FVector(1050, -3250, 450), FVector(1550, 750, 850)},
    {TEXT("Fin_Stbd"), FVector(1050, 3250, 450), FVector(1550, 750, 850)},
    {TEXT("Disc"), FVector(5303, 2508, 7127), FVector(9078, 8148, 5571)},
    {TEXT("Spire"), FVector(8047, 2598, -4993), FVector(5247, 6969, 6538)},
};
