"""Generate station ISM placement code from measured UE asset bounds.

Requires Artifacts/Refresh/vendor-meshes.json from the licensed local asset audit.
No vendor geometry/textures are copied into source control. Gameplay collision,
services and camera remain owned by SSStation. No Unreal launch is needed.
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "Artifacts/StationRefresh"


def author():
    OUT.mkdir(parents=True, exist_ok=True)
    inventory = json.loads((ROOT / "Artifacts/Refresh/vendor-meshes.json").read_text(encoding="utf-8"))
    source = {r["path"].split(".")[-1]: r for r in inventory if "/SciFiCorridor/Meshes/" in r["path"]}
    records = []

    def place(name, center, size=None, yaw=0, scale=1.0, role="shell"):
        row = source[name]
        origin, ext = row["origin"], row["extent"]
        factors = [scale]*3 if size is None else [size[i]/(2*ext[i]) for i in range(3)]
        angle = math.radians(yaw)
        def rotate(v):
            return [math.cos(angle)*v[0]-math.sin(angle)*v[1],
                    math.sin(angle)*v[0]+math.cos(angle)*v[1], v[2]]
        offset = rotate([origin[i]*factors[i] for i in range(3)])
        location = [center[i]-offset[i] for i in range(3)]
        world_ext = [abs(math.cos(angle))*ext[0]*factors[0]+abs(math.sin(angle))*ext[1]*factors[1],
                     abs(math.sin(angle))*ext[0]*factors[0]+abs(math.cos(angle))*ext[1]*factors[1],ext[2]*factors[2]]
        records.append(dict(mesh=row["path"],role=role,center=center,extent=world_ext,
                            location=location,scale=factors,yaw=yaw))

    # Near-native tile proportions; fill the existing 34 x 28 m floor footprint.
    # Top coincides with original decorative deck, 2.75 cm above collision deck.
    for x in range(17):
        for y in range(6):
            place("SM_Floor_01", [-1600+x*200, -1166.666667+y*466.666667, -15.2],
                  [200, 466.666667, 15.9], role="floor")
    # Wall panels remain outside service approach envelopes. Three native-height tiers
    # enclose a ship-sized bay without distorting a 3 m corridor wall to 10 m high.
    for side in (-1,1):
        for x in range(6):
            for tier in range(3):
                place("SM_Wall_03", [-1416.666667+x*566.666667,side*1400,150+tier*300],
                      [566.666667,100,300], yaw=0 if side==1 else 180)
        # Broad inbound opening stays completely empty through Y +/-700 cm.
        for tier in range(3):
            place("SM_Wall_03", [-1700,side*1075,150+tier*300], [750,50,300], yaw=90)
    for y in range(5):
        for tier in range(3):
            place("SM_Wall_03", [1710,-1120+y*560,150+tier*300], [560,50,300], yaw=90)
    # Roof clear of the full docking envelope (its minimum Z is 1000).
    for x in range(11):
        for y in range(6):
            place("SM_Celling_01", [-1545.454545+x*309.090909,-1166.666667+y*466.666667,1028],
                  [309.090909,466.666667,56], role="ceiling")
    # Close the 1m high clerestory using shallow matching upper wall trims.
    for side in (-1,1):
        for x in range(11):
            place("SM_Top_Wall02", [-1545.454545+x*309.090909,side*1400,950],
                  [309.090909,56,100], yaw=0 if side==1 else 180)
    for y in range(9):
        place("SM_Top_Wall02", [1710,-1244.444444+y*311.111111,950], [311.111111,50,100],yaw=90)
    # Decorative consoles sit against outer walls, never replace functional service actors.
    for x,side in [(-800,-1),(200,-1),(-1100,1),(0,1),(1000,1)]:
        place("SM_Monitor", [x,side*1325,190], yaw=180 if side==1 else 0,role="monitor")
        place("SM_MonitorScreen", [x,side*1318.5,190], yaw=180 if side==1 else 0,role="monitor")
    # Keep props in perimeter corners; retain all 280cm interaction radii unblocked.
    for x,y in [(1500,-1170),(1500,-1000),(-1450,-1200)]:
        place("SM_Crate", [x,y,60],role="prop")
    for x in (-1200,-600,0,600,1200):
        for y in (-950,950):
            place("SM_LampCelling", [x,y,990],scale=2.0,role="lamp")

    # Bounds-level clearance guard; presentation has no collision, but must not hide approach.
    for row in records:
        c,e = row['center'],row['extent']
        if row['role'] not in ('floor','ceiling','lamp'):
            assert not (c[0]-e[0]<450 and c[0]+e[0]>-1675 and
                        c[1]-e[1]<690 and c[1]+e[1]>-690 and
                        c[2]-e[2]<967.5 and c[2]+e[2]>0), row
    (OUT/'placements.json').write_text(json.dumps(records,indent=2),encoding='utf-8')
    paths = sorted({r['mesh'] for r in records})
    def vector(values):
        return "FVector(" + ", ".join(f"{v:.9f}" for v in values) + ")"
    lines = ["// Generated by Scripts/AuthorStationRefresh.py from measured licensed mesh bounds.",
             "// Presentation only. Keep SSStation collision and service locations authoritative.",
             '#include "Misc/PackageName.h"',
             '#include "SSStationPresentation.h"',
             "bool ASSStation::BuildLicensedShell()", "{",
             "    const TCHAR *Paths[] = {"]
    lines += [f'        TEXT("{path}"),' for path in paths]
    lines += ["    };", "    TArray<UStaticMesh *> Meshes;",
              "    for (const TCHAR *Path : Paths)", "    {",
              "        if (!FPackageName::DoesPackageExist(FPackageName::ObjectPathToPackageName(FString(Path))))",
              "            return false;",
              "        auto *Mesh = LoadObject<UStaticMesh>(nullptr, Path);",
              "        if (!Mesh)", "            return false;",
              "        Meshes.Add(Mesh);", "    }",
              "    // These two vendor meshes ship with an unassigned material slot.",
              "    // Resolve matching kit materials before creating any components.",
              "    TArray<UMaterialInterface *> MissingSlotMaterials;",
              "    MissingSlotMaterials.SetNumZeroed(Meshes.Num());",
              "    for (int32 Index = 0; Index < Meshes.Num(); ++Index)", "    {",
              "        for (const auto &Slot : Meshes[Index]->GetStaticMaterials())", "        {",
              "            if (Slot.MaterialInterface)", "                continue;",
              "            const TCHAR *FallbackPath = nullptr;",
              '            if (Meshes[Index]->GetFName() == TEXT("SM_MonitorScreen"))',
              '                FallbackPath = TEXT("/Game/SciFiCorridor/Materials/MI_MonitorError_Inst2.MI_MonitorError_Inst2");',
              '            else if (Meshes[Index]->GetFName() == TEXT("SM_Top_Wall02"))',
              '                FallbackPath = TEXT("/Game/SciFiCorridor/Materials/MI_CorridorWall_02.MI_CorridorWall_02");',
              "            if (!FallbackPath || !FPackageName::DoesPackageExist(FPackageName::ObjectPathToPackageName(FString(FallbackPath))))",
              "                return false;",
              "            MissingSlotMaterials[Index] = LoadObject<UMaterialInterface>(nullptr, FallbackPath);",
              "            if (!MissingSlotMaterials[Index])", "                return false;",
              "        }", "    }",
              "    TArray<UInstancedStaticMeshComponent *> Batches;",
              "    for (int32 Index = 0; Index < Meshes.Num(); ++Index)", "    {",
              '        auto *Batch = NewObject<UInstancedStaticMeshComponent>(this, FName(*FString::Printf(TEXT("LicensedStation_%d"), Index)));',
              "        Batch->SetupAttachment(RootComponent);",
              "        Batch->SetStaticMesh(Meshes[Index]);",
              "        const auto &Materials = Meshes[Index]->GetStaticMaterials();",
              "        for (int32 Slot = 0; Slot < Materials.Num(); ++Slot)",
              "            Batch->SetMaterial(Slot, SSStationPresentation::InstancedMaterial(Materials[Slot].MaterialInterface ? Materials[Slot].MaterialInterface.Get() : MissingSlotMaterials[Index]));",
              '        if (Meshes[Index]->GetFName() == TEXT("SM_MonitorScreen"))',
              "        {",
              '            const TCHAR *ScreenPath = TEXT("/Game/SpaceSurvival/Licensed/StationVisualPass/Screens/M_ServiceScreen");',
              "            if (FPackageName::DoesPackageExist(ScreenPath))",
              "                if (auto *Screen = LoadObject<UMaterialInterface>(nullptr, ScreenPath))",
              "                    Batch->SetMaterial(0, Screen);",
              "        }",
              '        Batch->SetCollisionProfileName(TEXT("NoCollision"));',
              "        Batch->SetCollisionEnabled(ECollisionEnabled::NoCollision);",
              "        Batch->SetGenerateOverlapEvents(false);",
              "        Batch->SetCanEverAffectNavigation(false);",
              "        Batch->SetMobility(EComponentMobility::Movable);",
              "        Batch->RegisterComponent();",
              "        Geometry.Add(Batch);", "        Batches.Add(Batch);", "    }"]
    for row in records:
        index = paths.index(row['mesh'])
        lines.append(f"    Batches[{index}]->AddInstance(FTransform(FRotator(0, {row['yaw']}, 0), {vector(row['location'])}, {vector(row['scale'])}));")
    lines += ["    SSStationPresentation::BuildDetails(this, Geometry);", "    return true;", "}", ""]
    (ROOT/'Source/SpaceSurvival/Private/SSStationRefresh.inl').write_text("\n".join(lines),encoding='utf-8')
    (OUT/'authoring.json').write_text(json.dumps(dict(instances=len(records),source_meshes=paths,
        output='Source/SpaceSurvival/Private/SSStationRefresh.inl',
        validation='Bounds clearance passed; runtime visuals/services/performance pending',
        merged_candidate='Rejected: material slots collapsed to grid; do not use'),indent=2),encoding='utf-8')


if __name__ == '__main__':
    author()
