"""Turn the pit stop receipt's collision boxes into the include ASSStation compiles against.

    python Scripts/GenerateStationPitStopBoxes.py --tag keel

The exterior mesh carries no collision of its own. Its solid parts are the slabs of the dock module
plus the disc and spire bounds, all measured in Blender in station-local centimetres and written to
Artifacts/StationPitStop/<tag>/PitStop.json. Regenerating this file is the only way the numbers reach
the game, so the visual and the collision cannot drift apart by hand.
"""
from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
argv = sys.argv[1:]
TAG = argv[argv.index('--tag') + 1] if '--tag' in argv else 'keel'
receipt = json.loads((ROOT / 'Artifacts/StationPitStop' / TAG / 'PitStop.json').read_text(encoding='utf-8'))
boxes = receipt['collision_boxes_cm']
imported = ROOT / 'Artifacts/StationPitStop' / TAG / 'Import.json'
assert imported.exists(), f'import first: {imported} records whether the glTF round trip mirrored Y'
import_info = json.loads(imported.read_text(encoding='utf-8'))
assert import_info['source_sha256'] == receipt['output_sha256'], 'Import.json is from a different GLB; import again'
Y_SIGN = int(import_info['y_sign'])
mouth = receipt['checks']['mouth_inner_opening']
assert mouth['y'] == [-700.0, 700.0] and mouth['z'] == [-10.0, 967.5] and mouth['x'] == -1700.0, mouth
lines = [
    '// Generated by Scripts/GenerateStationPitStopBoxes.py from Artifacts/StationPitStop/%s/PitStop.json.' % TAG,
    '// Station-local centimetres: centre then half-extent. Do not edit; regenerate.',
    '// Source blend sha256 %s, glb sha256 %s, Y sign %d (from Import.json).' % (receipt['source_sha256'][:16], receipt['output_sha256'][:16], Y_SIGN),
    'static const struct { const TCHAR *Name; FVector Center; FVector Extent; } SSStationPitStopBoxes[] = {',
]
for b in boxes:
    c, e = b['center'], b['extent']
    lines.append('    {TEXT("%s"), FVector(%d, %d, %d), FVector(%d, %d, %d)},' % (b['name'], c[0], Y_SIGN * c[1], c[2], e[0], e[1], e[2]))
lines.append('};')
out = ROOT / 'Source/SpaceSurvival/Private/SSStationPitStopBoxes.inl'
out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'{len(boxes)} boxes -> {out.relative_to(ROOT)}')
